[project]
name = "fusi-pybids-demo"
version = "0.0.10"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "catppuccin-jupyterlab>=0.2.4",
    "ipykernel>=6.29.5",
    "ipython>=8.30.0",
    "jupyterlab>=4.3.1",
    "pybids>=0.17.2",
]
